# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chore_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='housemate',
            name='email',
            field=models.EmailField(default='', max_length=200),
        ),
    ]
