# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chore_app', '0003_auto_20160315_1250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chore',
            options={},
        ),
    ]
