# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 22:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chore_app', '0004_auto_20160315_1300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chore',
            options={'ordering': ['due_date']},
        ),
    ]
