# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 03:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chore_app', '0005_auto_20160318_1757'),
        ('chore_app', '0004_login_signup'),
    ]

    operations = [
    ]
