# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-04 07:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chore_app', '0008_housemate_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housemate',
            name='house',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='house.House'),
            preserve_default=False,
        ),
    ]
