# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-04 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='house_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='house',
            name='zip_code',
            field=models.IntegerField(default=''),
        ),
    ]
