# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-04 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_auto_20160404_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='house_name',
            field=models.CharField(max_length=200),
        ),
    ]
